# Dubbo Config
spring:
  dubbo:
    application:
      name: gmall-item-consumer
      registry: zookeeper://192.168.67.130:2181
    consumer:
      time: 1000
  thymeleaf:
    cache: false
# port Config
server:
  port: 8084
